name: "Build"

on: 
  push:
    branches:
      - master

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

  run_tests:
    name: Run tests
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Build with Maven
      run: mvn --file pom.xml

    - name: Save cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

  upload_cov:
    name: Upload coverage
    needs: [setup, run_tests]
    runs-on: ubuntu-latest

    steps:
    - name: Upload to codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: target/site/jacoco/jacoco.xml
